# Generated by Django 3.2.8 on 2022-06-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userl', '0002_assigmnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigmnet',
            name='RoomCode',
            field=models.CharField(max_length=20),
        ),
    ]
