# Generated by Django 3.2.8 on 2022-06-05 08:11

from django.db import migrations, models
import teachl.models


class Migration(migrations.Migration):

    dependencies = [
        ('teachl', '0003_examdetails_examquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominfo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='Roomcode',
            field=models.CharField(default=teachl.models.gencode, max_length=7),
        ),
    ]
