# Generated by Django 3.2.8 on 2022-06-05 08:14

from django.db import migrations, models
import teachl.models


class Migration(migrations.Migration):

    dependencies = [
        ('teachl', '0004_auto_20220605_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='Roomcode',
            field=models.CharField(default=teachl.models.gencode, max_length=7, primary_key=True, serialize=False),
        ),
    ]
