# Generated by Django 3.2.8 on 2022-06-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachl', '0005_auto_20220605_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='assigmentdetals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigname', models.CharField(max_length=200)),
                ('assigdec', models.CharField(max_length=200)),
                ('RoomCode', models.CharField(max_length=7)),
                ('UniqCode', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('duedate', models.DateTimeField(max_length=200)),
                ('totalm', models.CharField(max_length=200)),
            ],
        ),
    ]
