# Generated by Django 3.2.8 on 2022-06-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachl', '0007_remove_assigmentdetals_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigmentdetals',
            name='RoomCode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='assigmentdetals',
            name='UniqCode',
            field=models.CharField(max_length=20),
        ),
    ]
